name: pr_bench
on: pull_request

jobs:
  bench:
    name: Benchmark
    runs-on: self-hosted
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v3
        name: Checkout PR base
        with:
          ref: ${{ github.base_ref }}
          submodules: true
      - uses: actions-rs/cargo@v1
        name: Benchmark PR base
        with:
          command: bench
          args: -- --save-baseline bl
      - uses: actions/checkout@v3
        name: Checkout merge commit
        with:
          ref: ${{ github.ref }}
          clean: false
          submodules: true
      - uses: actions-rs/cargo@v1
        name: Benchmark merge commit
        with:
          command: bench
          args: -- --baseline bl --color always
      
      - uses: chrnorm/deployment-action@main
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          ref: ${{ github.head_ref }}

      - uses: peaceiris/actions-gh-pages@v3
        name: Deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion
          destination_dir: ${{ github.ref_name }}
          exclude_assets: '**/*.json,**/*.csv'

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@main
        with:
          token: "${{ github.token }}"
          environment_url: https://ottojo.github.io/rust-bdd-ci/${{ github.ref_name }}/report/
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@main
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
